# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b68355b850e939f6c3db8465828f2cec3533b088e538e6a2a8a4f017a1d1dc196bc0b6a13aea5494a488f828aaed27f41a0cbce595167af6e3c9737340d0546d

test:
  secret_key_base: 337b38ca91b05f8c29ef35cb0283b45fcad4c536e83d9994db789143fee8a2898ba330e3da22b0ab39c8990581f92b0417dadcd071327b0110f9dd9211f16503

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
